# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "coverlet.collector"
      - dependency-name: "Codeuctivity.HtmlRenderer"
      - dependency-name: "nunit"
      - dependency-name: "SonarAnalyzer.CSharp"
      - dependency-name: "AngleSharp"
      - dependency-name: "Microsoft.NET.Test.Sdk"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
      - dependency-name: "Moq"
      - dependency-name: "xunit"
      - dependency-name: "xunit.runner.visualstudio"
      - dependency-name: "MSTest.TestAdapter"
      - dependency-name: "MSTest.TestFramework"
      - dependency-name: "Microsoft.SourceLink.GitHub"
      - dependency-name: "Codeuctivity.ImageSharpCompare"
      - dependency-name: "NUnit3TestAdapter"
      - dependency-name: "xunit.runner.console"